dev_algo_mysql: # 测试环境数据库
  host: 192.168.0.211
  port: 3306
  user: dev_algo_rw
  password: ybgkcQbpog7ck1glD~rz

local_pc_mysql: # 本地数据库
  host: localhost
  port: 3306
  user: root
  password: 931231

logger: # 日志
  log_path:
  log_name: mylog.log
  logger_name: my_logger