# -*- coding: utf-8 -*-
# socket连接信息
server:
  host: localhost
  port: 10002
  max_listen: 100

# 日志信息
logger: # 日志
  log_path: /home/logs/btr-algorithm-python/imagesreview
  log_name: mylog.log
  logger_name: my_logger

# 文件信息
image_path: image
model_path: resources/resnet18.model
vocabulary_path: resources/sensitive_vocabulary.txt
